modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="zekcraft"
version="1.0.2"
displayName="Zekcraft"
credits="Made with MCreator! https://mcreator.net ;)"
displayURL="https://sites.google.com/view/zekticezy"
logoFile="logo.png"
authors="zekticezy"
description='''
Make your game even WORSE!
'''

[[dependencies.zekcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




